### ISSUE TITLE
`BASE_URL` is undefined.

### ISSUE THREAD

**Issue by logue** [elmeet/vite-plugin-javascript-obfuscator#12]
I get the following error when building with this plugin.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'BASE_URL')
```

It seems that all the values in import.meta.env are not read. (such as `import.meta.env.DEV`)
Specifying `import.meta.env` or `import.meta.env.BASE_URL` in the reservedNames setting did not work.

```js
reservedNames: ['import.meta.env.BASE_URL']
```

How should I fix it?
I using vite v`4.4.9`.

**Comment by elmeet** [comment]
@logue  I cannot reproduce this issue. Can you provide a small example?

**Comment by logue** [comment]
In the end, the problem was resolved by explicitly updating the javascript-obfuscator as shown below.

```json
  "resolutions": {
    "javascript-obfuscator": "^4.1.0"
  }
```
