### ISSUE TITLE
index.cjs.js is not compatible with index.d.ts

### ISSUE THREAD

**Issue by kokororin** [elmeet/vite-plugin-javascript-obfuscator#14]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

But `index.cjs` missing a default export when using commonjs import.

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vite-plugin-javascript-obfuscator@3.0.3` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vite-plugin-javascript-obfuscator/dist/index.cjs.js b/node_modules/vite-plugin-javascript-obfuscator/dist/index.cjs.js
index 0478d53..3f5d136 100644
--- a/node_modules/vite-plugin-javascript-obfuscator/dist/index.cjs.js
+++ b/node_modules/vite-plugin-javascript-obfuscator/dist/index.cjs.js
@@ -49,3 +49,4 @@ function obfuscatorPlugin(obOptions) {
 }
 
 module.exports = obfuscatorPlugin;
+module.exports.default = obfuscatorPlugin;
```

**Comment by elmeet** [comment]
The compiler cannot simultaneously generate the following content:
```diff
module.exports = obfuscatorPlugin;
+module.exports.default = obfuscatorPlugin;
```
Due to incompatible changes, this issue will not be resolved.

**Comment by kokororin** [comment]
Now I use https://github.com/vitejs/vite-plugin-react/blob/main/scripts/patchCJS.ts to solve this problem
