### ISSUE TITLE
Vite+Vue3 Failed to resolve module specifier

### ISSUE THREAD

**Issue by OVYVO** [elmeet/vite-plugin-javascript-obfuscator#24]
When I used the obfuscatorPlugin to build the Vite+Vue3 project and deployed it to the server, the following error occurred
![image](https://github.com/user-attachments/assets/1b42510d-e772-449d-8ee5-9d65f045ba52)
I want to know if it's due to the lazy loading of the vue-router？
Has anyone encountered a similar problem before?
Thank you for your answer！

**Comment by OVYVO** [comment]
I solved the problem, thanks!

**Comment by yzwdzkn** [comment]
> 我解决了这个问题，谢谢！

请问你是怎么解决的？

**Comment by OVYVO** [comment]
> > 我解决了这个问题，谢谢！
> 
> 请问你是怎么解决的？

你这边报错情况跟我上述截图一样吗？如果是一样的话，可以尝试配置 exclude:[] 规则：排除你路由文件夹下的所有文件

**Comment by yzwdzkn** [comment]
> > > 我解决了这个问题，谢谢！
> > 
> > 
> > 请问你是怎么解决的？
> 
> 你报错类似情况上述截图一样吗？如果都一样的话，可以尝试配置排除:[] 规则：排除你路由文件夹下的所有文件
感谢，原来可以这么解决！！！

**Comment by yzwdzkn** [comment]
> > > 我解决了这个问题，谢谢！
> > 
> > 
> > 请问你是怎么解决的？
> 
> 你这边报错情况跟我上述截图一样吗？如果是一样的话，可以尝试配置 exclude:[] 规则：排除你路由文件夹下的所有文件

感谢，原来可以这么解决

**Comment by OVYVO** [comment]
> > > > 我解决了这个问题，谢谢！
> > > 
> > > 
> > > 请问你是怎么解决的？
> > 
> > 
> > 你这边报错情况跟我上述截图一样吗？如果是一样的话，可以尝试配置 exclude:[] 规则：排除你路由文件夹下的所有文件
> 
> 感谢，原来可以这么解决

不客气，你可以尝试一下，如果不能解决可以提新的issue
