### ISSUE TITLE
Error when build in nuxt 3

### ISSUE THREAD

**Issue by erisvn** [elmeet/vite-plugin-javascript-obfuscator#3]
![image](https://user-images.githubusercontent.com/69683870/229750747-e1cdd2ba-bc6f-44cd-8623-1730a375f063.png)

**Comment by elmeet** [comment]
@eris-vn Can you provide a minimization example?

**Comment by erisvn** [comment]
@elmeet https://stackblitz.com/edit/github-ftj7nb?file=nuxt.config.ts
