### ISSUE TITLE
How to use it with Svelte?

### ISSUE THREAD

**Issue by harryqt** [elmeet/vite-plugin-javascript-obfuscator#4]
Can you give us any example on how to use it with Svelte + Vite? Thanks!

**Comment by elmeet** [comment]
First use `vite` to generate the `svelte` template, and skip this step if the project has already been created.  For more information, please visit [https://vitejs.dev/guide/](https://vitejs.dev/guide/)
<img width="767" alt="image" src="https://user-images.githubusercontent.com/31975448/231033269-aaaecdf4-2250-41bd-a3f2-d9b57cb906ac.png">

Then install the `vite-plugin-javascript-obfuscator` dependency, and modify your `vite.config.js` or `vite.config.ts`. Read more in [README.md](https://github.com/elmeet/vite-plugin-javascript-obfuscator/blob/main/README.md)
```bash
npm install --save-dev vite-plugin-javascript-obfuscator
```
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/31975448/231035980-57139bcd-925c-4a91-9d01-285bd2a177cd.png">

Run the script command `npm run build`, you can see that the js file confusion in `/dist/assets/index-xxxx.js` has taken effect.

@Dibbyo456 Does the above solve your problem?

**Comment by harryqt** [comment]
Thank you it worked.! Awesome work. 🙏
