### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by g0dzcsgo** [elmeet/vite-plugin-javascript-obfuscator#8]
Is it possible to change what version this plugin uses? I wanna use a specific version of javascript obfuscator

**Comment by elmeet** [comment]
@g0dzcsgo  You can try this to solve your problem.
[https://stackoverflow.com/a/70396201](https://stackoverflow.com/a/70396201)


As of npm [v8.3](https://github.com/npm/cli/releases/tag/v8.3.0) (released with [Node.js 16](https://nodejs.org/en/download/releases)), remove `package-lock.json` and `node_modules`.  

Modify package.json, change to the version you want.
```
{
  "overrides": {
    "vite-plugin-javascript-obfuscator": {
      "javascript-obfuscator": "4.0.0"
    }
  }
}
```

Then run `npm install`
