### ISSUE TITLE
Code split not working

### ISSUE THREAD

**Issue by michioxd** [elmeet/vite-plugin-javascript-obfuscator#9]
Thanks for your works. I tried your plugin but my code split component is not included.

Before i use:
```
dist/assets/index-fa7db92d.css               548.02 kB │ gzip:    99.74 kB
dist/assets/Theatre-9280755c.js               18.35 kB │ gzip:     5.61 kB
dist/assets/index-dd76c81f.js              5,592.42 kB │ gzip: 1,300.29 kB
```

After:
```
dist/assets/index-fa7db92d.css               548.02 kB │ gzip:  99.74 kB
dist/assets/index-7f472e00.js              3,190.16 kB │ gzip: 748.10 kB
```

The `Theatre-9280755c.js` is code split module and it doesn't included after use obfuscator.

**Comment by elmeet** [comment]
@michioxd  I cannot reproduce this issue. Can you provide a small example?

Thanks!

**Comment by michioxd** [comment]
> @michioxd I cannot reproduce this issue. Can you provide a small example?
> 
> Thanks!

Here is a example:

```tsx
import { lazy } from "React";
import TheatreStyle from './Theatre.module.scss';

const Theatre = lazy(() => import('./Theatre')); // main problem

export default function TheatreProxy({ disableTheatre }) {

    return (
        <Theatre disableTheatre={disableTheatre} cls={TheatreStyle} />
    )
}
```

Vite must be bundle the `Theatre` file
Like this:
```
dist/assets/index-fa7db92d.css               548.02 kB │ gzip:    99.74 kB
dist/assets/Theatre-9280755c.js               18.35 kB │ gzip:     5.61 kB     # this
dist/assets/index-dd76c81f.js              5,592.42 kB │ gzip: 1,300.29 kB
```

But after i use your plugin, code splitter still work but cannot find the target file (`Theatre-<hash>.js`), it said 404.
I check the Vite build log and i didn't see the `Theatre-<hash>.js` file
```
dist/assets/index-fa7db92d.css               548.02 kB │ gzip:  99.74 kB
dist/assets/index-7f472e00.js              3,190.16 kB │ gzip: 748.10 kB
# it didn't bundle Theatre file, dist/assets/Theatre-<hash>.js not found
```

p/s: don't care about file size because i excluded `node_modules`.

**Comment by elmeet** [comment]
@michioxd  Hi, You can try adding the following line of option.

```javascript
    obfuscatorPlugin({
      options: {
        //...
        ignoreImports: true,
      },
    }),
```

**Comment by michioxd** [comment]
> @michioxd Hi, You can try adding the following line of option.
> 
> ```js
>     obfuscatorPlugin({
>       options: {
>         //...
>         ignoreImports: true,
>       },
>     }),
> ```

It's works, thanks so much!
